[versions]
appcompat-version = "1.7.1"
build-tools = "8.7.3"
coil-compose = "3.2.0"
compose-bom = "2025.05.01"
dokka-plugin = "1.7.20"
kotlin = "2.1.10"
kotlin-coroutines = "2.1.10"
kotlin-jvm = "2.1.10"
gson = "2.11.0"
ads-identifier = "18.2.0"
appset = "16.1.0"
billing = "7.1.1"
lifecycle = "2.8.7"
core-ktx = "1.15.0"
publish-sdk = "0.32.0"
junit = "4.13.2"
junit-version = "1.2.1"
espresso-core = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
compose-plugin = "2.0.0"
coroutines = "1.10.1"
ui-text-google-fonts = "1.8.2"
media3 = "1.4.1"

[libraries]
android-billing-client = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }
android-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "ads-identifier" }
android-appset = { module = "com.google.android.gms:play-services-appset", version.ref = "appset" }
appcompat-v171 = { module = "androidx.appcompat:appcompat", version.ref = "appcompat-version" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil-compose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil-compose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin-coroutines" }
android-lifecycle = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "ui-text-google-fonts" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "build-tools" }
android-compose-plugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-plugin" }
android-library = { id = "com.android.library", version.ref = "build-tools" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "publish-sdk" }
